AUDIO_FMT = 'wav'
AUDIO_SENTENCES_FILE_PATH = '/data/audio-sentences.json.txt'
BOOK_CLEAN_FILE_PATH = '/data/book-transcription.clean.json.txt'
BOOK_TRANSCRIPTION_FILE_PATH = '/data/book-transcription.txt'
GCS_BUCKET = 'plasmicai'
MAX_NEXT_WORD = 10
NORMALIZED_DIR_PATH = '/data/norm'
ORIGIN_AUDIO_FILE_PATH = '/data/origin.wav'
PART_DURATION = 5 * 60 * 60 # 5 hours in seconds
PARTS_DIR_PATH = '/data/parts'
PROJECT_NAME = 'nanaimobar'
SAMPLE_RATE = 16000 # 16 MHz audio sample rate
SEGMENT_DURATION = 60 # in seconds
SEGMENTS_DIR_PATH = '/data/segments'
SILENCE_AUDIO_FILE_PATH = '/data/silence.wav'
SILENCE_DIR_PATH = '/data/silence'
SPACY_MODEL = 'en_core_web_lg'
SPEECH_TO_TEXT_LANG = 'en-US'
TRANSCRIPTION_CLEAN_FILE_PATH = '/data/audio-transcription.clean.txt'
TRANSCRIPTION_FLAT_FILE_PATH = '/data/audio-transcription.flat.txt'
TRANSCRIPTIONS_DIR_PATH = '/data/transcriptions'
